FROM almalinux:8
# Architecture argument: amd64
ARG ARCH

RUN mkdir -p /var/log/siterm-agent/Agent && \
    mkdir -p /var/log/siterm-agent/Debugger/ && \
    mkdir -p /var/log/siterm-agent/Ruler/ && \
    mkdir -p /var/log/siterm-agent/QOS/ && \
    mkdir -p /var/log/siterm-agent/contentdb/ && \
    mkdir -p /opt/siterm/config && \
    mkdir -p sitermcode && \
    mkdir -p /var/log/supervisor && \
    mkdir -p /etc/supervisord.d/ && \
    mkdir -p /usr/local/sbin/ && \
    mkdir -p /usr/src/ && mkdir -p /etc/cron.d/ && \
    mkdir -p /etc/cron-scripts/

RUN yum -y install epel-release && yum clean all

RUN yum -y install git autoconf automake sudo libcurl-devel libffi-devel python3.12-lxml openssl-devel curl libuuid-devel lm_sensors ipset make nc python3.12 zlib-devel python3.12-devel wget jq iproute cronie python3.12-pip diffutils procps-ng mariadb-devel libxml2-devel libxslt-devel lldpd gawk iputils iproute iproute-tc automake autoconf gcc make pkgconfig traceroute fetch-crl && \
 yum clean all && \
 alternatives --set python3 /usr/bin/python3.12 && \
 python3.12 -m pip install --upgrade pip

# Install supervisord and superlance to run service, monitor mem usage
RUN pip3 install --no-cache-dir --upgrade setuptools pip && \
    pip3 install --no-cache-dir supervisor superlance

# Configure Supervisord
COPY build_files/etc/supervisord.conf /etc/

# Install CA Certs
RUN rpm -i https://repo.opensciencegrid.org/osg/24-main/el8/release/x86_64/Packages/o/osg-ca-certs-1.136-1.osg24.el8.noarch.rpm
# Install InCommon Server CA 2
COPY build_files/etc/grid-security/certificates/InCommon_RSA_Server_CA_2.pem /etc/grid-security/certificates/InCommon_RSA_Server_CA_2.pem
RUN chmod 644 "/etc/grid-security/certificates/InCommon_RSA_Server_CA_2.pem" && \
    ln -s "/etc/grid-security/certificates/InCommon_RSA_Server_CA_2.pem" "/etc/grid-security/certificates/$(openssl x509 -in /etc/grid-security/certificates/InCommon_RSA_Server_CA_2.pem -noout -hash).0"

# Install crons to fetch CA Certs
COPY build_files/etc/cron.d/fetch-crl /etc/cron.d/fetch-crl
COPY build_files/etc/cron.d/fetch-crl-reboot /etc/cron.d/fetch-crl-reboot
