ARG RELEASE=latest
FROM sdnsense/sitermdebugbase:$RELEASE

# Configuration which repo to use for build
ARG GITREPO=siterm
ARG GITORG=sdn-sense
ARG GITBR=master

RUN yum -y install traceroute tcpdump wireshark iperf3 java wget unzip && yum clean all
# Install FDT
RUN wget -nv https://github.com/fast-data-transfer/fdt/releases/download/0.27.0/fdt.jar -O /opt/fdt.jar
# Install Ethr
RUN wget -nv https://github.com/microsoft/ethr/releases/latest/download/ethr_linux.zip -O /opt/ethr_linux.zip && \
    unzip /opt/ethr_linux.zip -d /opt/ && rm -f /opt/ethr_linux.zip && chmod +x /opt/ethr

WORKDIR /opt/siterm/sitermcode
RUN git clone -b $GITBR https://github.com/$GITORG/$GITREPO
WORKDIR /opt/siterm/sitermcode/siterm/
RUN pip3 install --no-cache-dir -r requirements-agent.txt --upgrade || exit $?
RUN ./pre-install.sh "$RELEASE" && mv setup-agent.py setup.py && pip3 install --no-cache-dir . -v || exit $?
# Install all data files needed for Agent, e.g. crons
RUN cp packaging/general/siterm-crons /etc/cron.d/ && \
    cp packaging/general/siterm-ca-cron.sh /etc/cron-scripts/

# Copy Supervisor.d Config, Script files
COPY build_files/usr/local/sbin/ /usr/local/sbin/
COPY build_files/etc/supervisord.d/ /etc/supervisord.d/

HEALTHCHECK --retries=3 --start-period=60s --interval=60s --timeout=30s CMD bash /usr/local/sbin/docker-healthcheck.sh  || exit 1

CMD ["/usr/local/bin/supervisord", "-c", "/etc/supervisord.conf"]
